package kg.geektech.game.players;

public enum SuperAbility {
    CRITICAL_DAMAGE, HEAL, BOOST, SAVE_DAMAGE_AND_REVERT, BOSS_CANT_HIT, DEAD_AND_HELP, MAKE_A_JOKE,SHOOT_FROM_THE_EYES_AND_TAKE_SMALL_DAMAGE
}